#!/usr/bin/env bash
# ============================================================
# changelog.sh — Structured CHANGELOG from git history
#  
# ============================================================
set -euo pipefail

# --- Configuration ---
OUTPUT_FILE="${OUTPUT_FILE:-CHANGELOG.md}"
DRY_RUN=false
INCLUDE_ALL=false
SINCE_TAG=""

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --all)     INCLUDE_ALL=true; shift ;;
    --since)   SINCE_TAG="$2"; shift 2 ;;
    *)         SINCE_TAG="$1"; shift ;;
  esac
done

# --- Find last tag ---
if [[ -z "$SINCE_TAG" ]] && ! $INCLUDE_ALL; then
  SINCE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
  if [[ -z "$SINCE_TAG" ]]; then
    echo "⚠️  No git tags found. Use --all to include all commits or --since <tag>."
    exit 1
  fi
fi

# --- Build git log range ---
if $INCLUDE_ALL; then
  RANGE="HEAD"
  echo "📋 Including ALL commits (no tag filter)"
elif [[ -n "$SINCE_TAG" ]]; then
  RANGE="${SINCE_TAG}..HEAD"
  echo "📋 Commits since tag: $SINCE_TAG"
fi

# --- Fetch commits ---
COMMITS=$(git log "$RANGE" --pretty=format:"%s" --no-merges 2>/dev/null || true)
COMMIT_COUNT=$(echo "$COMMITS" | grep -c . 2>/dev/null || echo 0)

if [[ "$COMMIT_COUNT" -eq 0 ]]; then
  echo "📭 No commits found in range: $RANGE"
  echo "# Changelog" > "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "## [Unreleased]" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "_No changes since last release._" >> "$OUTPUT_FILE"
  exit 0
fi

echo "✅ Found $COMMIT_COUNT commits in range: $RANGE"

# --- Categorization ---
declare -a ADDED=() FIXED=() CHANGED=() REMOVED=() SECURITY=()

while IFS= read -r commit; do
  [[ -z "$commit" ]] && continue
  msg_lower=$(echo "$commit" | tr '[:upper:]' '[:lower:]')

  if   echo "$msg_lower" | grep -qE '^(feat|add|added)(\(.*?\))?:'; then
    ADDED+=("  - $commit")
  elif echo "$msg_lower" | grep -qE '^(fix|bug|hotfix|patch)(\(.*?\))?:'; then
    FIXED+=("  - $commit")
  elif echo "$msg_lower" | grep -qE '^(refactor|perf|style|chore|deps|ci|build|test|docs)(\(.*?\))?:'; then
    CHANGED+=("  - $commit")
  elif echo "$msg_lower" | grep -qE '^(remove|revert|drop|deprecate)(\(.*?\))?:'; then
    REMOVED+=("  - $commit")
  elif echo "$msg_lower" | grep -qE '^(security|vuln)(\(.*?\))?:'; then
    SECURITY+=("  - $commit")
  else
    CHANGED+=("  - $commit")
  fi
done <<< "$COMMITS"

# --- Generate output ---
{
  echo "# Changelog"
  echo ""
  echo "## [Unreleased]"
  echo ""

  if [[ ${#ADDED[@]} -gt 0 ]]; then
    echo "### Added"
    printf '%s\n' "${ADDED[@]}"
    echo ""
  fi

  if [[ ${#FIXED[@]} -gt 0 ]]; then
    echo "### Fixed"
    printf '%s\n' "${FIXED[@]}"
    echo ""
  fi

  if [[ ${#CHANGED[@]} -gt 0 ]]; then
    echo "### Changed"
    printf '%s\n' "${CHANGED[@]}"
    echo ""
  fi

  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    echo "### Removed"
    printf '%s\n' "${REMOVED[@]}"
    echo ""
  fi

  if [[ ${#SECURITY[@]} -gt 0 ]]; then
    echo "### Security"
    printf '%s\n' "${SECURITY[@]}"
    echo ""
  fi

  echo "---"
  echo "_Generated by [changelog.sh](https://github.com/claude-builders-bounty/claude-builders-bounty)_"
} > "$OUTPUT_FILE"

# --- Report ---
echo "📝 Generated $OUTPUT_FILE:"
echo "   Added:    ${#ADDED[@]} entries"
echo "   Fixed:    ${#FIXED[@]} entries"
echo "   Changed:  ${#CHANGED[@]} entries"
echo "   Removed:  ${#REMOVED[@]} entries"
echo "   Security: ${#SECURITY[@]} entries"

if $DRY_RUN; then
  echo ""
  echo "--- Preview (dry-run) ---"
  cat "$OUTPUT_FILE"
fi
